#!/usr/bin/env python2
#
# The MIT License (MIT)
#
# Copyright (c) 2015 Anders Steen Christensen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
#
# Citations:
#   (1) J Rezac and P Hobza (2012) J. Chem. Theory Comput., 8:141-151
#   (2) AS Christensen (2015) https://github.com/andersx/pauli-se
#


import sys
from pauli_api import calc_pauli


if __name__ == "__main__":

    # Import some parameters.
    from parameters import SHH, EHH, R0HH

    # Get XYZ-filename.
    filename = sys.argv[1]

    # Calculate energy, defining filename and parameters.
    energy = calc_pauli(filename, SHH, EHH, R0HH)

    # Output results in kcal/mol.
    print "Pauli repulsion: %6.4f kcal/mol" % energy
